name: Portal CI

on:
  push:
    branches: ["**"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install pnpm
        run: |
          npm install --global pnpm

      - name: Dependency cache
        uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-portal-v1-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install pnpm
        run: |
          npm install --global pnpm

      - name: Dependency cache
        uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-portal-v1-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
